apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-phase: sync
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-root-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    template:
      type: Opaque
  dataFrom:
    - find:
        path: CLOUDFLARE_API_TOKEN