apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.0/cert-manager.yaml
  - cloudflare-token.external-secret.yaml
  - cluster-issuers.yaml
  - wildcard-certificate.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager
        namespace: cert-manager
      spec:
        template:
          spec:
            containers:
            - name: cert-manager
              image: quay.io/jetstack/cert-manager-controller:v1.17.0
              args:
              - --leader-election-namespace=cert-manager
              - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
              - --dns01-recursive-nameservers-only
    target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager 