apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - cert-manager.1.17.0.yaml
  - cloudflare-token.external-secret.yaml
  - cluster-issuers.yaml
  - wildcard-certificate.yaml

patches:
  - patch: |-
      # - op: test
      #   path: /spec/template/spec/containers/0/args/2
      #   value: --leader-election-namespace=kube-system
      # - op: replace
      #   path: /spec/template/spec/containers/0/args/2
      #   value: --leader-election-namespace=cert-manager
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --dns01-recursive-nameservers-only
    target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager 