# This ExternalSecret is a troubleshooting tool that fetches all available secrets from Infisical.
# It can be temporarily deployed to any namespace to verify:
# - ClusterSecretStore connectivity
# - Available secrets and their paths
# - Proper authentication
#
# Usage:
# 1. Copy this file to your namespace
# 2. Update the namespace field
# 3. Apply the file
# 4. Check the created secret: kubectl get secret debug-all-secrets -n <namespace> -o yaml
# 5. Delete when done troubleshooting
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: debug-all-secrets
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-phase: sync
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-root-secret-store
    kind: ClusterSecretStore
  target:
    name: debug-all-secrets
    template:
      type: Opaque
  dataFrom:
    - find:
        name:
          regexp: ".*" 