apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical-root-secret-store
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-phase: sync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-auth-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-auth-credentials
      # Details to pull secrets from
      secretsScope:
        projectSlug: platform-gi0-x
        environmentSlug: dev # "dev", "staging", "prod", etc..
        # optional
        secretsPath: / # Root is "/"
        # optional
        recursive: true # Default is false
      # optional
      hostAPI: https://app.infisical.com