apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secrets.0.14.2.yaml
  - infisical.secret-store.yaml
  # External Secrets Operator resources...
  - cloudflare-tunnel.namespace.yaml
  - cloudflare-tunnel-token.external-secret.yaml
  - cloudflare-tunnel-id.external-secret.yaml