apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cloudflare Tunnel Configuration
# This sets up a Cloudflare tunnel for secure ingress
# Dependencies:
# - External Secrets Operator
# - Gateway API
# - Cloudflare account with tunnel configured

namespace: cloudflare-tunnel

resources:
  - tunnel-config.yaml
  - deployment.yaml
  - network-policy.yaml
  - pdb.yaml
  - rbac.yaml

replacements:
  # Keep only the HTTPRoute annotation replacement
  - source:
      kind: ConfigMap
      name: cloudflare-tunnel-config
      namespace: cloudflare-tunnel
      fieldPath: data.tunnel-url
    targets:
      - select:
          kind: HTTPRoute
        fieldPaths:
          - metadata.annotations.external-dns.alpha.kubernetes.io/target 