apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-updater
  namespace: cloudflare-tunnel
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["cloudflare-tunnel-config"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudflared-configmap-updater
  namespace: cloudflare-tunnel
subjects:
- kind: ServiceAccount
  name: cloudflared
  namespace: cloudflare-tunnel
roleRef:
  kind: Role
  name: configmap-updater
  apiGroup: rbac.authorization.k8s.io 