apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-id
  namespace: cloudflare-tunnel
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-phase: sync
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-root-secret-store
  target:
    name: cloudflare-tunnel-id
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
  dataFrom:
    - find:
        path: CLOUDFLARE_TUNNEL_ID 